"""Collision tests for the rule layer. Run from backend/:   python -m tests.test_collisions   (ends with ALL PASSED)

Checks that mistakes which reach the SAME wrong answer are separated by the working, that a case the working cannot
separate makes the engine abstain instead of guessing, and that correct working raises no alarm.
These cases are generated by app/datagen.py; they are a regression guard, NOT an accuracy estimate.
"""
from app import datagen
from app.diagnose import ACCEPT_THRESHOLD
from app.rules import Q, Ctx, run_rules, resolve_id, mark_ambiguous, Finding, AMBIGUOUS_CONF


def _best(c):
    q = Q(id=c["qid"], text=c["text"], expected=c["expected"], candidates=c["cands"])
    fs = run_rules(Ctx(q, c["steps"], c["final"]))
    return fs, (max(fs, key=lambda f: f.confidence) if fs else None)


def check_case(c):
    fs, b = _best(c)
    accepted = b is not None and b.confidence >= ACCEPT_THRESHOLD
    if c["status"] == "diagnosed":
        return accepted and resolve_id(b.kind, c["cands"]) == c["gold"], (b.kind, b.confidence) if b else None
    if c["status"] == "insufficient":
        return not accepted, (b.kind, b.confidence) if b else None
    if c["status"] == "correct":
        return not fs, [f.kind for f in fs]
    return not any(f.kind == "DISTRIBUTION" and f.confidence >= ACCEPT_THRESHOLD for f in fs), [f.kind for f in fs]


def main():
    fails, n = [], 0
    pools = [datagen.build(seed=7), datagen.build(seed=11),
             datagen.build(seed=3, roots=range(6, 13), cd=range(5, 9), xs=range(7, 13))]
    for cases in pools:
        for c in cases:
            ok, got = check_case(c)
            n += 1
            if not ok:
                fails.append((c["qid"], c["status"], c["gold"], got))
    # the collisions are real: a final-answer-only classifier cannot beat 1/3 on them
    coll = [c for c in pools[0] if c["status"] != "correct"]
    assert abs(datagen.final_only_bound(coll) - 1 / 3) < 1e-9, "collision groups no longer share a final answer"
    # ambiguity handling: a different-id alternative caps confidence below the acceptance threshold
    f = mark_ambiguous(Finding("DISTRIBUTION", 1, "x", confidence=0.95), ["TRANSPOSITION_SLIP"])
    assert f.confidence == AMBIGUOUS_CONF < ACCEPT_THRESHOLD
    # an alternative that maps to the SAME id must not cause an abstention
    g = mark_ambiguous(Finding("DISC_PLUS", 0, "x", confidence=0.88), ["DISC_C_SIGN"])
    assert g.confidence == 0.88
    # discriminant: both mechanisms that give the same number are reported, not just the first
    q = Q(id="t", text="Find the discriminant of 2x² + 3x - 2 = 0.")
    fs = run_rules(Ctx(q, [], "D = -7"))
    assert fs and "DISC_C_SIGN" in fs[0].alternatives and "sign of c" in fs[0].evidence
    if fails:
        for f_ in fails:
            print("FAIL", f_)
        raise SystemExit(f"{len(fails)} of {n} cases failed")
    print(f"{n} collision cases checked")
    print("ALL PASSED")


if __name__ == "__main__":
    main()
